//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db_test_02
{
    using System;
    using System.Collections.Generic;
    
    public partial class DH_warehouse_table
    {
        public string ItemID { get; set; }
        public string ItemName { get; set; }
        public string ItemWhere { get; set; }
    }
}
